export interface CarRental {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  phone: string;
  imageURL: string | null;
  gender: number;
  address: string;
  city: string;
  governorateId: number;
  governorateName: string | null;
  countryId: number;
  countryName: string | null;
  dateOfBirth: string;
  emailConfirmed: boolean;
  status: number;
  userType: number;
  nationalDocsURL: string;
  acquisitionDate: string;
  assetId: string;
  assetName: string;
  description: string;
  credentialDocURL: string;
  assetEmail: string;
  verificationNotes: string | null;
  assetGovernateId: number;
  assetGovernateName: string | null;
  latitude: number;
  longitude: number;
  locationDescription: string | null;
  facilities: string[] | null;
  openingTime: string;
  closingTime: string;
  languagesSupported: string[] | null;
  assetType: number;
  starRating?: number;
  hasPool?: boolean;
  hasRestaurant?: boolean;
  fuelTypes?: number[];
  models?: string[];
  transmission?: number;
  rentalPolicies?: string[];
} 